#! /usr/bin/env zsh

__numonic_edit_zshrc() {
	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man edit-zshrc
				return 0
				;;
			*?)
				print-fail "edit-zshrc: unknown argument ${1}"
				man edit-zshrc | cat 1>&2
				return 1
				;;
			*)
				break;
		esac
		shift
	done

	{
		if [ -n "${debug:-}" ]; then
			print-warn 'edit-bashrc: debug enabled'
			set -x
		fi

		zshrc_path="${NUMONIC_CONFIG}/zshrc"

		if [ ! -d "${NUMONIC_CONFIG}" ]; then
			mkdir "${NUMONIC_CONFIG}"
		fi

		if [ ! -f "${zshrc_path}" ]; then
			printf "%s\n\n" "#! /usr/bin/env zsh" > "${zshrc_path}"
		fi

		chmod +x "${zshrc_path}"
		${EDITOR:-vi} "${zshrc_path}"
	}
}

__numonic_edit_zshrc
