#! /usr/bin/env bash

# set shell
export NUMONIC_SHELL="bash"

# add scripts to path
export PATH="${NUMONIC_HOME}/bash/scripts:${PATH}"

# shell options
shopt -s checkwinsize	# check window size on script exit
shopt -s cdable_vars	# enable change directory to a variable value
shopt -s extglob		# enable extended glob patterns
shopt -s nullglob		# enable nullglob

export HISTCONTROL=ignoreboth

# system binds for bash completion (for interactive terminals)
if [ -t 0 ] && [ -t 1 ]; then
	bind "set completion-ignore-case on" 2>/dev/null	# ignore strict case sensitivity
	bind "set bell-style none" 2>/dev/null				# turn off audible alerts
	bind "set show-all-if-ambiguous on" 2>/dev/null		# show completion with double tap
fi

# evaluate eval scripts
for eval_script in "${NUMONIC_HOME}"/bash/scripts/eval/*; do
	if [ ! -f "${eval_script}" ]; then
		break
	fi

	. "${eval_script}"
done

# test for user bashrc
if [ -f "${NUMONIC_SHARE}"/bashrc ]; then
	. "${NUMONIC_SHARE}"/bashrc
fi
