ARG DISTRO=ubuntu
ARG TAG=latest
FROM ${DISTRO}:${TAG}

ARG NUMONIC_SHELL=bash

WORKDIR /repo
COPY . .

VOLUME /var/lib/containers
VOLUME /home/numonic/.local/share/containers

RUN ./hack/pre.sh numonic
USER numonic

ENV NUMONIC_CONTAINER="true" \
    _CONTAINERS_USERNS_CONFIGURED=""

RUN set -e; \
    ./install-numonic --shell="${NUMONIC_SHELL}"; \
    cp containers/entrypoint.sh /home/numonic/.local/bin/entrypoint; \
    ./containers/clean.sh --force

WORKDIR /home/numonic
ENTRYPOINT [ "/home/numonic/.local/bin/entrypoint" ]
