#! /usr/bin/env sh

set -e

__numonic_container_update() {
	runtimes=

	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man container-update
				return 0
				;;
			-q|--quiet)
				quiet=1
				;;
			-r|--runtime)
				runtimes="${runtimes} ${2}"
				shift
				;;
			--runtime=*)
				runtimes="${runtimes} ${1#*=}"
				;;
			--)
				shift
				break
				;;
			*?)
				runtimes="${runtimes} ${1}"
				;;
			*)
				break;
		esac
		shift
	done

	if [ -z "${runtimes:-}" ]; then
		runtimes="docker nerdctl podman"
	fi

	for runtime in ${runtimes}; do
		if command -v "${runtime}" 1>/dev/null 2>&1; then
			(
				if [ -n "${quiet:-}" ]; then
					exec 1>/dev/null
				fi

				if [ -n "${debug:-}" ]; then
					set -x
				fi

				print-warn "container-update: updating images in ${runtime}..." 2>&1
				"${runtime}" "$@" image ls \
					--format "{{.Repository}}:{{.Tag}}" | xargs -L1 "${runtime}" pull 2>/dev/null
			) || true

			found=1
		fi
	done

	if [ -z "${found:-}" ]; then
		print-fail 'container-update: no container runtimes were available on the path.'
		man container-update | cat 1>&2
		return 1
	fi
}

__numonic_container_update "$@"
