#! /usr/bin/env sh

set -e

__numonic_container_gc() {
	runtimes=

	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man container-gc
				return 0
				;;
			-q|--quiet)
				quiet=1
				;;
			-r|--runtime)
				runtimes="${runtimes} ${2}"
				shift
				;;
			--runtime=*)
				runtimes="${runtimes} ${1#*=}"
				;;
			--)
				shift
				break
				;;
			*?)
				runtimes="${runtimes} ${1}"
				;;
			*)
				break
		esac
		shift
	done

	if [ -z "${runtimes:-}" ]; then
		runtimes="docker nerdctl podman"
	fi

	for runtime in ${runtimes}; do
		if command -v "${runtime}" 1>/dev/null 2>&1; then
			(
				if [ -n "${quiet:-}" ]; then
					exec 1>/dev/null
				fi

				if [ -n "${debug:-}" ]; then
					set -x
				fi

				print-warn "container-gc: garbage collecting ${runtime}..." 2>&1
				"${runtime}" "$@" container prune --force 2>/dev/null || true
				"${runtime}" "$@" volume prune --force 2>/dev/null || true
				"${runtime}" "$@" image prune --all --force 2>/dev/null || true
			) || true

			found=1
		fi
	done

	if [ -z "${found:-}" ]; then
		print-fail 'container-gc: no container runtimes were available on the path.'
		man container-gc | cat 1>&2
		return 1
	fi
}

__numonic_container_gc "$@"
