#! /usr/bin/env sh

set -e

__numonic_git_commit_amend() {
	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man git commit-amend
				return 0
				;;
			-q|--quiet)
				quiet=1
				;;
			*?)
				print-fail "git commit-amend: too many arguments, argument: ${1} is unexpected"
				man git commit-amend | cat 1>&2
				return 1
				;;
			*)
				break;
		esac
		shift
	done

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		if [ -n "${quiet:-}" ]; then
			exec 1>/dev/null
		fi

		git add --all
		git commit --amend --signoff
	)
}

__numonic_git_commit_amend "$@"
