#! /usr/bin/env sh

set -e

__numonic_git_start() {

	branch=
	origin=
	upstream="upstream"
	ref=

	while :; do
		case $1 in
			-dr|--dry-run)
				dry_run=1
				;;
			-d|--debug)
				debug=1
				;;
			-b|--branch)
				branch="${2}"
				shift
				;;
			--branch=*)
				branch="${1#*=}"
				;;
			-r|-o|--remote|--origin)
				origin="${2}"
				shift
				;;
			--remote=*|--origin=*)
				origin="${1#*=}"
				;;
			-u|--upstream)
				upstream="${2}"
				shift
				;;
			--upstream=*)
				upstream="${1#*=}"
				;;
			-ref|-sp|--ref|--start-point)
				ref="${2}"
				shift
				;;
			--ref=*|--start-point=*)
				ref="${1#*=}"
				;;
			-h|--help)
				man git-start
				return 0
				;;
			?*)
				if [ -z "${branch:-}" ]; then
					branch="${1}"
				elif [ -z "${origin:-}" ]; then
					origin="${1}"
				elif [ -z "${ref:-}" ]; then
					ref="${1}"
				else
					print-fail "git-start: too many arguments, argument: ${1} is unexpected"
					man git-start | cat 1>&2
					return 1
				fi
				;;
			*)
				break
				;;
		esac
		shift
	done

	if [ -z "${origin:-}" ]; then
		origin="origin"
	fi

	if [ -z "${ref:-}" ]; then
		ref="HEAD"
	fi

	if [ -z "${branch}" ]; then
		print-fail "git start: a branch name must be specified"
		man git-start | cat 1>&2
		return 1
	fi

	for current in develop next main master; do
		if git show-ref --quiet --verify "refs/heads/${current}"; then
			main="${current}"
			break
		fi
	done

	if [ -z "${main:-}" ]; then
		upstream=
	fi

	print-warn '' \
		'GIT START' \
		'' \
		'ORIGIN INFO' \
		"remote : ${origin}" \
		"branch : ${branch}" \
		"ref    : ${ref}" \
		'' \
		'UPSTREAM INFO' \
		"remote : ${upstream:-"n/a"}" \
		"ref    : ${main:-"n/a"}" \
	''

	if [ -n "${dry_run:-}" ]; then
		return 0
	fi

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		# attempt to pull from the origin
		git pull "${origin}" || true

		# determine if we are on a fork
		if [ -n "${main:-}" ]; then
			git pull --rebase "${upstream}" "${main}"
			git push || true
		fi

		# create the new branch
		git switch --force-create "${branch}" "${ref}"
		git push --set-upstream "${origin}" "${branch}"
	)
}

__numonic_git_start "$@"
