#! /usr/bin/env sh

set -e

__numonic_git_commit_restore() {
	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man git-commit-restore
				return 0
				;;
			*)
				break;
		esac
		shift
	done

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		git restore --source=HEAD^ --staged "${*:-.}"
	)
}

__numonic_git_commit_restore "$@"
