#! /usr/bin/env sh

set -e

__numonic_git_update() {
	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man git-update
				return 0
				;;
			*)
				break;
		esac
		shift
	done

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		git fetch --prune --prune-tags
		git pull --rebase "$@"
		git submodule update --init --recursive
	)
}
