#! /usr/bin/env sh

set -e

__numonic_git_edit_config() {
	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man git-edit-config
				return 0
				;;
			*)
				break;
		esac
		shift
	done

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		git config --global --edit "$@"
	)
}

__numonic_git_edit_config "$@"
