#! /usr/bin/env sh

set -e

__numonic_git_delete_gone() {
	remotes=

	while :; do
		case $1 in
			--help)
				man git-delete-gone
				return 0
				;;
			-dr|--dry-run)
				dry_run=1
				;;
			--debug)
				debug=1
				;;
			--remote)
				remotes="${remotes} ${2}"
				shift
				;;
			--remote=*)
				remote="${remotes} ${1#*=}"
				;;
			?*)
				remotes="${remotes} ${1}"
				;;
			*)
				break
				;;
		esac
		shift
	done

	if [ -z "${remotes:-}" ]; then
		remotes=$(git remote)
	fi


	print-warn '' 'GIT DELETE GONE'

	for remote in ${remotes}; do
		print-warn "remote: ${remote}"
	done

	printf '\n'

	if [ -n "${dry_run:-}" ]; then
		return 0
	fi

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		for remote in ${remotes}; do
			git fetch --prune "${remote}"

			if [ "${remote}" = "upstream" ]; then
				git fetch --prune-tags --force "${remote}"
			fi
		done

		git branch --verbose \
			| grep 'gone]' \
			| cut -d ' ' -f 3 \
			| xargs git branch --delete --force 2>/dev/null
	)
}

__numonic_git_delete_gone "$@"
