#! /usr/bin/env sh

set -e

__numonic_install_detect_secrets() {
	install_dir="${NUMONIC_SHARE}/detect-secrets"

	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-h|--help)
				man install-detect-secrets
				return 0
				;;
			-f|--force)
				if [ -d "${install_dir}" ]; then
					rm -rf "${install_dir}"
				fi

				if command -v detect-secrets 1>/dev/null 2>&1; then
					print-fail "install-detect-secrets: detect-secrets is already on the path at: $(command -v detect-secrets)" \
						'This version was not installed using numonic.' \
						'Please remove using the package manager that was used to install it.'
					return 1
				fi
				;;
			?*)
				print-fail "install-detect-secrets: too many arguments, argument: ${1} is unexpected"
				man install-detect-secrets | cat 1>&2
				return 1
				;;
			*)
				break
				;;
		esac
		shift
	done

	if command -v detect-secrets 1>/dev/null 2>&1; then
		print-warn "install-detect-secrets: detect-secrets is already on the path at: $(command -v detect-secrets)" \
			'to reinstall, use the --force flag'
		return 1
	fi

	if command -v python3 1>/dev/null 2>&1; then
		python_cmd=$(command -v python3)
	elif command -v python 1>/dev/null 2>&1; then
		python_cmd=$(command -v python)
	elif command -v install-python 1>/dev/null 2>&1; then
		install-python
		python_cmd=$(command -v python3 || command -v python)
	else
		print-fail "install-detect-secrets: neither python3 nor python is available on the PATH." \
			"please install python3 via a package manager"
		man install-detect-secrets | cat 1>&2
		return 1
	fi

	(
		if [ -n "${debug:-}" ]; then
			set -x
		fi

		print-warn 'install-detect-secrets: creating virtual environment for detect-secrets...' 2>&1
		"${python_cmd}" -m venv "${install_dir}"

		python_cmd="${install_dir}"/bin/python

		print-warn 'install-detect-secrets: upgrading pip in virtual environment...'  2>&1
		"${python_cmd}" -m pip install --upgrade pip 1>/dev/null 2>&1

		print-warn 'install-detect-secrets: installing detect-secrets, this may take a minute or two...'  2>&1
		"${python_cmd}" -m pip install --upgrade detect-secrets 1>/dev/null 2>&1

		ln -fs "${install_dir}"/bin/detect-secrets "${NUMONIC_BIN}"
	)

	print-success 'install-detect-secrets: the detect-secrets is now ready'
}

__numonic_install_detect_secrets "$@"
