#! //usr/bin/env sh
# shellcheck disable=SC2059

set -e

__numonic_print_success()
{
	printf "${CLR_SUCCESS}"
	printf '%s\n' "$@"
	printf "${CLR_SUCCESS}${FORMAT_CLEAR}"
}

__numonic_print_success "$@"
