#! /usr/bin/env sh

set -e

__numonic_reverse() {
	reversed=

	# shellcheck disable=SC2068
	for value in $@; do
		reversed="${value} ${reversed}"
	done

	# shellcheck disable=SC2086
	printf '%s\n' ${reversed%*' '}
}

__numonic_reverse "$@"
