#! /usr/bin/env sh

set -e

if ! command gpg-connect-agent 1>/dev/null 2>&1; then
	print-fail "switch-smart-card: the gpg connect agent is missing -- do you have gpg installed?"
	exit 1
fi

# relearn the smart card
gpg-connect-agent updatestartuptty "scd serialno" "learn --force" /bye

# print the card status
gpg --card-status
