.TH "CODE-WAIT" "1" "November 18, 2021" "Numonic v1.0.0" "Numonic Manual"
.nh \" Turn off hyphenation by default.
.SH NAME
.PP
code-wait - enables Visual Studio Code to be used as an editor with support for waiting for the editor to be closed
before proceeding.
.SH SYNOPSIS
.PP
\f[B]code-wait\f[R] [<\f[I]args...\f[R]>]
.SH DESCRIPTION
.PP
This command is an internal tool used to enable using Visual Studio code as a command line editor.
When the \f[C]code\f[R] executable is available on the command line, numonic will configure the \f[C]EDITOR\f[R]
environment variable to use this command.
The \f[C]EDITOR\f[R] environment variable is only set if it is not already set by the user.
.PP
If \f[C]code\f[R] is not available when this command is invoked, then \f[C]vi\f[R] will be used as the editor.
.SH OPTIONS
.SS ARGUMENTS
.SS <args>
.PP
the arguments to pass to the editor, such as the path of the file to open all arguments
.SH EXAMPLES
.SS code-wait \[ti]/.gitconfig
.PP
opens Visual Studio Code as the editor for the file \f[I]\[ti]/.gitconfig\f[R] and waits for the editor window to be
closed before proceeding
.SH SEE ALSO
.PP
\f[B]editor\f[R](1)
.SH AUTHORS
Deavon M. McCaffery; Not Committed Yet
