#! /usr/bin/env sh

set -e

__numonic_install_pandoc() {
	install-brew-formulae \
		--name=pandoc \
		--tap=homebrew/cask \
		--brew=pandoc \
		--brew=librsvg \
		--brew=basictex \
		"$@"

	while :; do
		case $1 in
			-d|--debug)
				debug=1
				;;
			-q|--quiet)
				quiet=1
				;;
			?*)
				;;
			*)
				break
				;;
		esac
		shift
	done

	(
		if [ -n "${quiet:-}" ]; then
			exec 1>/dev/null
		fi

		if [ -n "${debug:-}" ]; then
			set -x
		fi

		eval "$(/usr/libexec/path_helper -s)"

		print-warn '' \
			'install-pandoc: you will be asked for admin credentials to install tex plugins' \
		''

		sudo tlmgr update --self || true
		sudo tlmgr install texliveonfly || true
		sudo tlmgr install xelatex || true
		sudo tlmgr install adjustbox || true
		sudo tlmgr install tcolorbox || true
		sudo tlmgr install collectbox || true
		sudo tlmgr install ucs || true
		sudo tlmgr install environ || true
		sudo tlmgr install trimspaces || true
		sudo tlmgr install titling || true
		sudo tlmgr install enumitem || true
		sudo tlmgr install rsfs || true

		print-success 'install-pandoc: pandoc is ready'
	)
}

__numonic_install_pandoc "$@"
