name: end-to-end

on:
  pull_request:
    branches:
      - main
      - next

concurrency:
  group: end-to-end-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: shellcheck
        run: ./hack/lint-shell.sh
      - name: hadolint
        uses: docker://ghcr.io/hadolint/hadolint:latest
        with:
          args: hadolint Containerfile

  nix:
    name: "end-to-end-${{ matrix.os }}-${{ matrix.shell }}"
    runs-on: ${{ matrix.os }}
    needs:
      - lint
    strategy:
      matrix:
        shell:
          - bash
          - zsh
        os:
          - macos-10.15
          - macos-11.0
          - ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: ./install-numonic --shell="${{ matrix.shell }}"
      - name: test
        run: ./hack/test.sh

  win:
    name: "end-to-end-${{ matrix.os }}-${{ matrix.shell }}"
    runs-on: ${{ matrix.os }}
    needs:
      - lint
    strategy:
      matrix:
        shell:
          - bash
          - zsh
        os:
          - windows-2019
          - windows-2022
    defaults:
      run:
        shell: wsl-sh -u build {0}
    steps:
      - name: setup-wsl
        uses: vampire/setup-wsl@v1
        with:
          wsl-shell-command: /bin/sh -e
      - name: checkout
        uses: actions/checkout@v2
      - name: create-user
        run: ./hack/pre.sh
        shell: wsl-sh -u root {0}
      - name: install
        run: ./install-numonic --shell="${{ matrix.shell }}"
      - name: test
        run: ./hack/test.sh
